### ISSUE TITLE
Could not find assembly AspNetCore.Identity.DocumentDB (while deploying 2.0 version beta-5)

### ISSUE THREAD

**Issue by vindemi** [FelschR/AspNetCore.Identity.DocumentDB#47] opened 2019-01-22 08:51 UTC
Hey there, I have a problem with deploying web application (api .net core) on Azure. Locally it works good but when I try to publish it into cloud I get this error:
![image](https://user-images.githubusercontent.com/5741988/51523122-3ef23b00-1e2b-11e9-87c5-375a5f37d5bd.png)

Does it reffer to this issue?
https://stackoverflow.com/questions/25551816/could-not-load-file-or-assembly-windows-azure-website/25552523

**Comment by FelschR** [comment] 2019-01-22 10:10
This issue is related to #43.
I've looked into it and the build server was misconfigured and thus only produced a 64 bit library.
All the automated tests work fine on 32 bit so I'm currently preparing a new release which will be compatible with the "Any CPU" platform target.

**Comment by FelschR** [comment] 2019-01-22 10:35
closing as duplicate of #43

**Closed by FelschR** 2019-01-22 10:35 UTC
